[server]
port = 8580
headless = true
enableCORS = false
enableXsrfProtection = false
maxUploadSize = 500

[browser]
gatherUsageStats = false

[theme]
base = "light"
primaryColor = "#36A9E1"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F4F8FC"
textColor = "#3C3C3B"
font = "DM Sans"
